version: "3.8"

services:

  ###############################################################
  # Inventory-service returns a simple REST call to get inventory 
  ###############################################################
  inventory-service:
    image: onestopdevops/inventory-service:1.0
    container_name: inventory-service
    build: ./inventory-service
    restart: always
    ports:
      - 8081:8081
  

